const ZONAS_TRAFICO = [
    { id: "centro", nombre: "Centro" },
    { id: "retiro", nombre: "Retiro" },
    { id: "salamanca", nombre: "Salamanca" },
    { id: "chamberi", nombre: "Chamberí" },
    { id: "arganzuela", nombre: "Arganzuela" },
];

const DATOS_TRAFICO = {
    "centro": [
        { punto: "Gran Vía", intensidad: 1200, velocidad: 15, ocupacion: 85 },
        { punto: "Alcalá", intensidad: 980, velocidad: 22, ocupacion: 70 },
        { punto: "Sol", intensidad: 1500, velocidad: 10, ocupacion: 95 },
        { punto: "Mayor", intensidad: 750, velocidad: 30, ocupacion: 55 },
        { punto: "Arenal", intensidad: 430, velocidad: 40, ocupacion: 30 },
        { punto: "Preciados", intensidad: 1100, velocidad: 18, ocupacion: 80 },
        { punto: "Fuencarral", intensidad: 860, velocidad: 25, ocupacion: 65 },
        { punto: "Montera", intensidad: 920, velocidad: 20, ocupacion: 72 },
        { punto: "Hortaleza", intensidad: 670, velocidad: 35, ocupacion: 48 },
        { punto: "Carretas", intensidad: 540, velocidad: 38, ocupacion: 40 },
        { punto: "Atocha", intensidad: 1300, velocidad: 12, ocupacion: 90 },
        { punto: "Paseo del Prado", intensidad: 1050, velocidad: 20, ocupacion: 75 },
    ],
    "retiro": [
        { punto: "Av. Menéndez Pelayo", intensidad: 870, velocidad: 28, ocupacion: 62 },
        { punto: "Ibiza", intensidad: 650, velocidad: 33, ocupacion: 47 },
        { punto: "Doctor Esquerdo", intensidad: 720, velocidad: 30, ocupacion: 52 },
        { punto: "Narváez", intensidad: 590, velocidad: 36, ocupacion: 43 },
        { punto: "Luca de Tena", intensidad: 480, velocidad: 42, ocupacion: 35 },
        { punto: "Av. Ciudad de Barcelona", intensidad: 1100, velocidad: 20, ocupacion: 78 },
        { punto: "Pacífico", intensidad: 930, velocidad: 24, ocupacion: 68 },
        { punto: "Retiro", intensidad: 410, velocidad: 45, ocupacion: 28 },
        { punto: "O'Donnell", intensidad: 780, velocidad: 29, ocupacion: 57 },
        { punto: "Sainz de Baranda", intensidad: 860, velocidad: 26, ocupacion: 63 },
        { punto: "Conde de Casal", intensidad: 700, velocidad: 31, ocupacion: 50 },
    ],
    "salamanca": [
        { punto: "Serrano", intensidad: 950, velocidad: 24, ocupacion: 68 },
        { punto: "Goya", intensidad: 1100, velocidad: 19, ocupacion: 79 },
        { punto: "Velázquez", intensidad: 820, velocidad: 27, ocupacion: 60 },
        { punto: "Príncipe de Vergara", intensidad: 1050, velocidad: 21, ocupacion: 75 },
        { punto: "Castelló", intensidad: 690, velocidad: 33, ocupacion: 50 },
        { punto: "Jorge Juan", intensidad: 760, velocidad: 30, ocupacion: 55 },
        { punto: "Ayala", intensidad: 580, velocidad: 37, ocupacion: 42 },
        { punto: "Lagasca", intensidad: 870, velocidad: 25, ocupacion: 64 },
        { punto: "Maldonado", intensidad: 500, velocidad: 40, ocupacion: 36 },
        { punto: "Hermosilla", intensidad: 930, velocidad: 23, ocupacion: 70 },
        { punto: "Lista", intensidad: 640, velocidad: 35, ocupacion: 46 },
    ],
    "chamberi": [
        { punto: "Bravo Murillo", intensidad: 1150, velocidad: 18, ocupacion: 82 },
        { punto: "Santa Engracia", intensidad: 880, velocidad: 25, ocupacion: 64 },
        { punto: "Alonso Cano", intensidad: 720, velocidad: 30, ocupacion: 52 },
        { punto: "Raimundo Fernández Villaverde", intensidad: 990, velocidad: 22, ocupacion: 72 },
        { punto: "Cea Bermúdez", intensidad: 650, velocidad: 34, ocupacion: 47 },
        { punto: "Fuencarral", intensidad: 860, velocidad: 26, ocupacion: 62 },
        { punto: "Trafalgar", intensidad: 540, velocidad: 38, ocupacion: 39 },
        { punto: "Génova", intensidad: 1020, velocidad: 20, ocupacion: 74 },
        { punto: "Sagasta", intensidad: 780, velocidad: 28, ocupacion: 57 },
        { punto: "Ríos Rosas", intensidad: 670, velocidad: 32, ocupacion: 49 },
        { punto: "Eloy Gonzalo", intensidad: 490, velocidad: 41, ocupacion: 35 },
    ],
    "arganzuela": [
        { punto: "Paseo de las Delicias", intensidad: 1080, velocidad: 20, ocupacion: 77 },
        { punto: "Embajadores", intensidad: 930, velocidad: 23, ocupacion: 68 },
        { punto: "Legazpi", intensidad: 850, velocidad: 27, ocupacion: 61 },
        { punto: "Acacias", intensidad: 620, velocidad: 35, ocupacion: 45 },
        { punto: "Toledo", intensidad: 780, velocidad: 29, ocupacion: 57 },
        { punto: "Imperial", intensidad: 540, velocidad: 39, ocupacion: 39 },
        { punto: "Chopera", intensidad: 460, velocidad: 43, ocupacion: 33 },
        { punto: "Méndez Álvaro", intensidad: 1200, velocidad: 17, ocupacion: 86 },
        { punto: "Pirámides", intensidad: 700, velocidad: 31, ocupacion: 51 },
        { punto: "Pradillo", intensidad: 580, velocidad: 37, ocupacion: 42 },
        { punto: "Atocha Renfe", intensidad: 1350, velocidad: 14, ocupacion: 92 },
    ],
};